#ifndef HW_CONFIG_H
#define HW_CONFIG_H

#include "gpio.h"

#define RED_LED_DIR DDRD
#define RED_LED_PORT PORTD
#define RED_LED_BIT PD3
#define GREEN_LED_DIR DDRD
#define GREEN_LED_PORT PORTD
#define GREEN_LED_BIT PD4
#define BUZZER_DIR DDRD
#define BUZZER_PORT PORTD
#define BUZZER_BIT PD5

#define INIT_RED_LED() SET_GPIO_DIR_OUT(RED_LED_DIR, RED_LED_BIT)
#define INIT_GREEN_LED() SET_GPIO_DIR_OUT(GREEN_LED_DIR, GREEN_LED_BIT)
#define INIT_BUZZER() SET_GPIO_DIR_OUT(BUZZER_DIR, BUZZER_BIT)
#define TURN_RED_LED_ON()  SET_GPIO_HI(RED_LED_PORT, RED_LED_BIT)
#define TURN_RED_LED_OFF() SET_GPIO_LO(RED_LED_PORT, RED_LED_BIT)
#define TURN_GREEN_LED_ON()  SET_GPIO_HI(GREEN_LED_PORT, GREEN_LED_BIT)
#define TURN_GREEN_LED_OFF() SET_GPIO_LO(GREEN_LED_PORT, GREEN_LED_BIT)
#define TURN_BUZZER_ON()  SET_GPIO_HI(BUZZER_PORT, BUZZER_BIT)
#define TURN_BUZZER_OFF() SET_GPIO_LO(BUZZER_PORT, BUZZER_BIT)

#endif // HW_CONFIG_H
