#ifndef HW_CONFIG_H
#define HW_CONFIG_H

#include <avr/io.h>
#include "gpio.h"

#define RED_LED_DIR DDRD
#define RED_LED_PORT PORTD
#define RED_LED_BIT PD3

#define GREEN_LED_DIR DDRD
#define GREEN_LED_PORT PORTD
#define GREEN_LED_BIT PD4

#define BUZZER_DIR DDRD
#define BUZZER_PORT PORTD
#define BUZZER_BIT PD5

#define BUTTON1_DIR DDRB
#define BUTTON1_PORT PORTB
#define BUTTON1_PIN PINB
#define BUTTON1_BIT PB0

#define BUTTON2_DIR DDRB
#define BUTTON2_PORT PORTB
#define BUTTON2_PIN PINB
#define BUTTON2_BIT PB1

#define BUTTON3_DIR DDRB
#define BUTTON3_PORT PORTB
#define BUTTON3_PIN PINB
#define BUTTON3_BIT PB2

#define BUTTON4_DIR DDRB
#define BUTTON4_PORT PORTB
#define BUTTON4_PIN PINB
#define BUTTON4_BIT PB3

#define BUTTON5_DIR DDRB
#define BUTTON5_PORT PORTB
#define BUTTON5_PIN PINB
#define BUTTON5_BIT PB4

#define BUTTON6_DIR DDRB
#define BUTTON6_PORT PORTB
#define BUTTON6_PIN PINB
#define BUTTON6_BIT PB5

#define BUTTON7_DIR DDRB
#define BUTTON7_PORT PORTB
#define BUTTON7_PIN PINB
#define BUTTON7_BIT PB6

#define BUTTON8_DIR DDRB
#define BUTTON8_PORT PORTB
#define BUTTON8_PIN PINB
#define BUTTON8_BIT PB7

#define INIT_RED_LED() SET_GPIO_DIR_OUT(RED_LED_DIR, RED_LED_BIT)
#define INIT_GREEN_LED() SET_GPIO_DIR_OUT(GREEN_LED_DIR, GREEN_LED_BIT)
#define INIT_BUZZER() SET_GPIO_DIR_OUT(BUZZER_DIR, BUZZER_BIT)
#define INIT_BUTTON1 SET_GPIO_DIR_IN(BUTTON1_DIR, BUTTON1_BIT)
#define INIT_BUTTON2 SET_GPIO_DIR_IN(BUTTON2_DIR, BUTTON2_BIT)
#define INIT_BUTTON3 SET_GPIO_DIR_IN(BUTTON3_DIR, BUTTON3_BIT)
#define INIT_BUTTON4 SET_GPIO_DIR_IN(BUTTON4_DIR, BUTTON4_BIT)
#define INIT_BUTTON5 SET_GPIO_DIR_IN(BUTTON5_DIR, BUTTON5_BIT)
#define INIT_BUTTON6 SET_GPIO_DIR_IN(BUTTON6_DIR, BUTTON6_BIT)
#define INIT_BUTTON7 SET_GPIO_DIR_IN(BUTTON7_DIR, BUTTON7_BIT)
#define INIT_BUTTON8 SET_GPIO_DIR_IN(BUTTON8_DIR, BUTTON8_BIT)

#define PULL_UP_ENABLE_BUTTON1() SET_GPIO_HI(BUTTON1_PORT, BUTTON1_PIN)
#define PULL_UP_ENABLE_BUTTON2() SET_GPIO_HI(BUTTON2_PORT, BUTTON2_PIN)
#define PULL_UP_ENABLE_BUTTON3() SET_GPIO_HI(BUTTON3_PORT, BUTTON3_PIN)
#define PULL_UP_ENABLE_BUTTON4() SET_GPIO_HI(BUTTON4_PORT, BUTTON4_PIN)
#define PULL_UP_ENABLE_BUTTON5() SET_GPIO_HI(BUTTON5_PORT, BUTTON5_PIN)
#define PULL_UP_ENABLE_BUTTON6() SET_GPIO_HI(BUTTON6_PORT, BUTTON6_PIN)
#define PULL_UP_ENABLE_BUTTON7() SET_GPIO_HI(BUTTON7_PORT, BUTTON7_PIN)
#define PULL_UP_ENABLE_BUTTON8() SET_GPIO_HI(BUTTON8_PORT, BUTTON8_PIN)

#define TURN_RED_LED_ON()  SET_GPIO_HI(RED_LED_PORT, RED_LED_BIT)
#define TURN_RED_LED_OFF() SET_GPIO_LO(RED_LED_PORT, RED_LED_BIT)
#define TURN_GREEN_LED_ON()  SET_GPIO_HI(GREEN_LED_PORT, GREEN_LED_BIT)
#define TURN_GREEN_LED_OFF() SET_GPIO_LO(GREEN_LED_PORT, GREEN_LED_BIT)
#define TURN_BUZZER_ON()  SET_GPIO_HI(BUZZER_PORT, BUZZER_BIT)
#define TURN_BUZZER_OFF() SET_GPIO_LO(BUZZER_PORT, BUZZER_BIT)

#define BUTTON1_PRESSED() GET_GPIO_INPUT(BUTTON1_PIN, BUTTON1_BIT)
#define BUTTON2_PRESSED() GET_GPIO_INPUT(BUTTON2_PIN, BUTTON2_BIT)
#define BUTTON3_PRESSED() GET_GPIO_INPUT(BUTTON3_PIN, BUTTON3_BIT)
#define BUTTON4_PRESSED() GET_GPIO_INPUT(BUTTON4_PIN, BUTTON4_BIT)
#define BUTTON5_PRESSED() GET_GPIO_INPUT(BUTTON5_PIN, BUTTON5_BIT)
#define BUTTON6_PRESSED() GET_GPIO_INPUT(BUTTON6_PIN, BUTTON6_BIT)
#define BUTTON7_PRESSED() GET_GPIO_INPUT(BUTTON7_PIN, BUTTON7_BIT)
#define BUTTON8_PRESSED() GET_GPIO_INPUT(BUTTON8_PIN, BUTTON8_BIT)

#endif // HW_CONFIG_H
